In [ ]:
# Librerias

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go

In [ ]:
# Parametros

umbral_pico = 0.4
maq_obj = 'PLE1'

tol_pct = 0.05 # tolerancia para determinar si la señal esta dentro de la media 
t_estable = pd.Timedelta(seconds=10) # Tiempo minimo que tiene que pasar la señal cerca de la media para considerar que el evento termino

FASES = ['R', 'S', 'T']

In [ ]:
# Leer rutas

from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[1]
DATA_PATH = PROJECT_ROOT / "data"

print("PROJECT_ROOT:", PROJECT_ROOT)
print("DATA_PATH:", DATA_PATH)
print("Existe data:", DATA_PATH.exists())

PROJECT_ROOT: c:\Users\HP Spectre X360\Desktop\MARIANA\COLLOQUIA_2025\Analisis_Powermeter
DATA_PATH: c:\Users\HP Spectre X360\Desktop\MARIANA\COLLOQUIA_2025\Analisis_Powermeter\data
Existe data: True

In [ ]:
# Abrir los graficos en el navegador

pio.renderers.default = 'browser'

In [ ]:
# Funcion para cargar datos

from pathlib import Path
import pandas as pd

def cargar_maquina(base_path, maquina):
    base_path = Path(base_path).resolve()
    paths = list((base_path / maquina).rglob("*.csv"))

    if not paths:
        raise ValueError(f"No se encontraron CSV para {maquina} en {base_path}")

    dfs = []
    for path in paths:
        df = pd.read_csv(path)
        df["maquina"] = maquina
        dfs.append(df)

    return (
        pd.concat(dfs, ignore_index=True)
          .sort_values("temporal_placa")
          .reset_index(drop=True)
    )

In [ ]:
# Carga de datos

df_ple1 = cargar_maquina(DATA_PATH, "PLE1")
df_ple7 = cargar_maquina(DATA_PATH, "PLE7")

In [ ]:
# Funcion preparar_df

def preparar_df(df):
    df = df.copy()

    # Timestamp
    df['temporal_placa'] = pd.to_datetime(df['temporal_placa'])
    df['hora'] = df['temporal_placa'].dt.hour
    df['minuto'] = df['temporal_placa'].dt.minute

    # Turnos
    def asignar_turno(hora, minuto):
        t = hora * 60 + minuto

        # Pausas
        if 12*60 <= t < 12*60 + 30:
            return 'ALMUERZO'
        if 22*60 <= t < 22*60 + 30:
            return 'CENA'

        # Turnos
        if 5*60 <= t < 17*60:
            return 'TURNO MAÑANA'
        if 17*60 <= t < 22*60:
            return 'TURNO TARDE'
        if (t >= 22*60 + 30) or (t < 1*60):
            return 'TURNO TARDE'

        return 'FUERA_TURNO'

    df['turno'] = df.apply(
        lambda x: asignar_turno(x['hora'], x['minuto']),
        axis=1
    )
        
    # Potencias totales por timestamp
    df['p_activa_total'] = (
        df['potencia_a_r'] +
        df['potencia_a_s'] +
        df['potencia_a_t']
    )

    df['q_reactiva_total'] = (
        df['potencia_r_r'] +
        df['potencia_r_s'] +
        df['potencia_r_t']
    )

    return df

In [ ]:
# Ajuste de datos de las plegadoras

df_ple1 = preparar_df(df_ple1)
df_ple7 = preparar_df(df_ple7)

df_all = pd.concat([df_ple1, df_ple7], ignore_index=True)

# Filtra los datos correspondientes al 9-1-2026
import datetime as dt

dia = dt.date(2026, 1, 12)
df_all = df_all[df_all['temporal_placa'].dt.date == dia]

In [ ]:
# Calculo la media de las corrientes excluyendo los picos

def media_sin_picos(s, q = 0.9):
    return s[s <= s.quantile(q)].mean()

medias_por_fase = (
    df_all[df_all['maquina'] == maq_obj]
    .assign(
        R=df_all['corriente_r'],
        S=df_all['corriente_s'],
        T=df_all['corriente_t'],
    )
    .melt(
        id_vars=['maquina'],
        value_vars=['R', 'S', 'T'],
        var_name='fase',
        value_name='corriente'
    )
    .groupby(['maquina', 'fase'], as_index=False)
    .agg(
        baseline=('corriente', media_sin_picos)
    )
)

In [ ]:
# Funcion detectar_picos

def detectar_picos(signal, timestamp, umbral_pico):
    dt = timestamp.diff().dt.total_seconds()
    valid = dt > 0

    dI_dt = signal.diff() / dt

    return (
        valid &
        dI_dt.notna() &
        (dI_dt > umbral_pico)
    )

In [ ]:
# Detección de picos en las 3 fases

import pandas as pd

maquinas = df_all['maquina'].unique()

fase_cols = {
    'R': 'corriente_r',
    'S': 'corriente_s',
    'T': 'corriente_t'
}

df_peaks_list = []

for maq in maquinas:

    g = (
        df_all[df_all['maquina'] == maq]
        .sort_values('temporal_placa')
        .copy()
    )

    if g.empty:
        continue

    for fase, col_corriente in fase_cols.items():

        señal = g[col_corriente]
        timestamp = g['temporal_placa']

        idx_picos = detectar_picos(señal, timestamp, umbral_pico)

        if len(idx_picos) == 0:
            continue

        df_peaks = g.loc[idx_picos, ['temporal_placa']].copy()
        df_peaks['maquina'] = maq
        df_peaks['fase'] = fase    

        df_peaks_list.append(df_peaks)

# DataFrame final de picos
df_peaks_all = pd.concat(df_peaks_list, ignore_index=True)

df_peaks_all['temporal_placa'] = (
    pd.to_datetime(df_peaks_all['temporal_placa'], errors='coerce')
    .dt.tz_localize(None)
)

In [ ]:
# Visualizacion de picos detectados y su marca temporal

df_peaks_all = df_peaks_all.sort_values(
    by=['maquina', 'fase']
).reset_index(drop=True)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

df_peaks_all

          temporal_placa maquina fase
0    2026-01-12 05:00:36    PLE1    R
1    2026-01-12 05:00:38    PLE1    R
2    2026-01-12 05:20:18    PLE1    R
3    2026-01-12 05:20:31    PLE1    R
4    2026-01-12 05:20:36    PLE1    R
5    2026-01-12 05:20:51    PLE1    R
6    2026-01-12 05:23:30    PLE1    R
7    2026-01-12 05:23:40    PLE1    R
8    2026-01-12 05:24:03    PLE1    R
9    2026-01-12 05:26:55    PLE1    R
10   2026-01-12 05:27:10    PLE1    R
11   2026-01-12 05:27:15    PLE1    R
12   2026-01-12 05:27:20    PLE1    R
13   2026-01-12 05:30:55    PLE1    R
14   2026-01-12 05:31:12    PLE1    R
15   2026-01-12 05:31:25    PLE1    R
16   2026-01-12 05:31:48    PLE1    R
17   2026-01-12 05:31:53    PLE1    R
18   2026-01-12 05:32:05    PLE1    R
19   2026-01-12 05:32:13    PLE1    R
20   2026-01-12 05:35:52    PLE1    R
21   2026-01-12 05:36:25    PLE1    R
22   2026-01-12 05:40:25    PLE1    R
23   2026-01-12 05:40:35    PLE1    R
24   2026-01-12 05:40:45    PLE1    R
25   2026-01-12 05:40:50    PLE1    R
26   2026-01-12 05:45:16    PLE1    R
27   2026-01-12 05:45:33    PLE1    R
28   2026-01-12 05:45:46    PLE1    R
29   2026-01-12 05:47:52    PLE1    R
30   2026-01-12 05:47:57    PLE1    R
31   2026-01-12 05:48:12    PLE1    R
32   2026-01-12 05:48:17    PLE1    R
33   2026-01-12 05:50:34    PLE1    R
34   2026-01-12 05:50:51    PLE1    R
35   2026-01-12 05:51:01    PLE1    R
36   2026-01-12 05:51:04    PLE1    R
37   2026-01-12 05:51:06    PLE1    R
38   2026-01-12 05:51:12    PLE1    R
39   2026-01-12 05:51:37    PLE1    R
40   2026-01-12 05:52:02    PLE1    R
41   2026-01-12 05:52:17    PLE1    R
42   2026-01-12 05:54:13    PLE1    R
43   2026-01-12 05:55:21    PLE1    R
44   2026-01-12 05:55:29    PLE1    R
45   2026-01-12 05:55:34    PLE1    R
46   2026-01-12 05:55:52    PLE1    R
47   2026-01-12 05:56:14    PLE1    R
48   2026-01-12 06:02:06    PLE1    R
49   2026-01-12 06:02:11    PLE1    R
50   2026-01-12 06:02:26    PLE1    R
51   2026-01-12 06:06:16    PLE1    R
52   2026-01-12 06:06:23    PLE1    R
53   2026-01-12 06:06:53    PLE1    R
54   2026-01-12 06:07:04    PLE1    R
55   2026-01-12 06:07:16    PLE1    R
56   2026-01-12 06:08:12    PLE1    R
57   2026-01-12 06:08:22    PLE1    R
58   2026-01-12 06:08:29    PLE1    R
59   2026-01-12 06:11:31    PLE1    R
60   2026-01-12 06:11:36    PLE1    R
61   2026-01-12 06:11:44    PLE1    R
62   2026-01-12 06:11:49    PLE1    R
63   2026-01-12 06:12:01    PLE1    R
64   2026-01-12 06:12:06    PLE1    R
65   2026-01-12 06:13:52    PLE1    R
66   2026-01-12 06:14:08    PLE1    R
67   2026-01-12 06:14:10    PLE1    R
68   2026-01-12 06:17:50    PLE1    R
69   2026-01-12 06:17:55    PLE1    R
70   2026-01-12 06:18:08    PLE1    R
71   2026-01-12 06:18:35    PLE1    R
72   2026-01-12 06:18:38    PLE1    R
73   2026-01-12 06:18:48    PLE1    R
74   2026-01-12 06:20:16    PLE1    R
75   2026-01-12 06:20:31    PLE1    R
76   2026-01-12 06:20:39    PLE1    R
77   2026-01-12 06:20:42    PLE1    R
78   2026-01-12 06:20:44    PLE1    R
79   2026-01-12 06:22:38    PLE1    R
80   2026-01-12 06:22:40    PLE1    R
81   2026-01-12 06:22:48    PLE1    R
82   2026-01-12 06:23:00    PLE1    R
83   2026-01-12 06:23:08    PLE1    R
84   2026-01-12 06:23:58    PLE1    R
85   2026-01-12 06:24:06    PLE1    R
86   2026-01-12 06:24:14    PLE1    R
87   2026-01-12 06:24:29    PLE1    R
88   2026-01-12 06:24:31    PLE1    R
89   2026-01-12 06:24:44    PLE1    R
90   2026-01-12 06:25:02    PLE1    R
91   2026-01-12 06:25:09    PLE1    R
92   2026-01-12 06:25:32    PLE1    R
93   2026-01-12 06:25:34    PLE1    R
94   2026-01-12 06:25:42    PLE1    R
95   2026-01-12 06:26:17    PLE1    R
96   2026-01-12 06:26:33    PLE1    R
97   2026-01-12 06:26:38    PLE1    R
98   2026-01-12 06:26:43    PLE1    R
99   2026-01-12 06:39:58    PLE1    R
100  2026-01-12 06:40:06    PLE1    R
101  2026-01-12 06:40:28    PLE1    R
102  2026-01-12 06:40:36    PLE1    R
103  2026-01-12 06:40:43    PLE1    R
104  2026-01-12 06:42:40    PLE1    R
105  2026-01-12 06:42:55    PLE1    R
106  2026-01-12 06:43:00    PLE1    R
107  2026-01-12 06:43:07    PLE1    R
108  2026-01-12 06:43:12    PLE1    R
109  2026-01-12 06:43:17    PLE1    R
110  2026-01-12 06:43:22    PLE1    R
111  2026-01-12 06:44:43    PLE1    R
112  2026-01-12 06:44:46    PLE1    R
113  2026-01-12 06:44:51    PLE1    R
114  2026-01-12 06:44:56    PLE1    R
115  2026-01-12 06:45:16    PLE1    R
116  2026-01-12 06:45:29    PLE1    R
117  2026-01-12 06:46:01    PLE1    R
118  2026-01-12 06:46:09    PLE1    R
119  2026-01-12 06:46:24    PLE1    R
120  2026-01-12 06:48:28    PLE1    R
121  2026-01-12 06:49:23    PLE1    R
122  2026-01-12 06:49:28    PLE1    R
123  2026-01-12 06:49:54    PLE1    R
124  2026-01-12 06:49:56    PLE1    R
125  2026-01-12 06:50:16    PLE1    R
126  2026-01-12 06:50:27    PLE1    R
127  2026-01-12 06:50:34    PLE1    R
128  2026-01-12 06:50:39    PLE1    R
129  2026-01-12 06:51:22    PLE1    R
130  2026-01-12 06:52:53    PLE1    R
131  2026-01-12 06:52:58    PLE1    R
132  2026-01-12 06:53:08    PLE1    R
133  2026-01-12 06:54:54    PLE1    R
134  2026-01-12 06:54:57    PLE1    R
135  2026-01-12 06:55:12    PLE1    R
136  2026-01-12 06:55:30    PLE1    R
137  2026-01-12 06:55:35    PLE1    R
138  2026-01-12 06:57:08    PLE1    R
139  2026-01-12 06:57:11    PLE1    R
140  2026-01-12 06:57:18    PLE1    R
141  2026-01-12 06:57:36    PLE1    R
142  2026-01-12 06:58:04    PLE1    R
143  2026-01-12 06:58:44    PLE1    R
144  2026-01-12 06:59:14    PLE1    R
145  2026-01-12 06:59:27    PLE1    R
146  2026-01-12 06:59:30    PLE1    R
147  2026-01-12 06:59:32    PLE1    R
148  2026-01-12 07:01:08    PLE1    R
149  2026-01-12 07:02:19    PLE1    R
150  2026-01-12 07:02:24    PLE1    R
151  2026-01-12 07:02:39    PLE1    R
152  2026-01-12 07:02:49    PLE1    R
153  2026-01-12 07:02:54    PLE1    R
154  2026-01-12 07:07:32    PLE1    R
155  2026-01-12 07:07:45    PLE1    R
156  2026-01-12 07:07:55    PLE1    R
157  2026-01-12 07:10:39    PLE1    R
158  2026-01-12 07:10:44    PLE1    R
159  2026-01-12 07:11:07    PLE1    R
160  2026-01-12 07:11:34    PLE1    R
161  2026-01-12 07:11:57    PLE1    R
162  2026-01-12 07:12:17    PLE1    R
163  2026-01-12 07:12:20    PLE1    R
164  2026-01-12 07:14:11    PLE1    R
165  2026-01-12 07:14:16    PLE1    R
166  2026-01-12 07:14:26    PLE1    R
167  2026-01-12 07:14:44    PLE1    R
168  2026-01-12 07:19:37    PLE1    R
169  2026-01-12 07:19:42    PLE1    R
170  2026-01-12 07:20:12    PLE1    R
171  2026-01-12 07:20:27    PLE1    R
172  2026-01-12 07:21:18    PLE1    R
173  2026-01-12 07:21:30    PLE1    R
174  2026-01-12 07:21:33    PLE1    R
175  2026-01-12 07:21:43    PLE1    R
176  2026-01-12 07:21:53    PLE1    R
177  2026-01-12 07:21:56    PLE1    R
178  2026-01-12 07:26:08    PLE1    R
179  2026-01-12 07:26:18    PLE1    R
180  2026-01-12 07:26:21    PLE1    R
181  2026-01-12 07:26:26    PLE1    R
182  2026-01-12 07:26:28    PLE1    R
183  2026-01-12 07:27:47    PLE1    R
184  2026-01-12 07:27:54    PLE1    R
185  2026-01-12 07:27:59    PLE1    R
186  2026-01-12 07:28:07    PLE1    R
187  2026-01-12 07:28:25    PLE1    R
188  2026-01-12 07:28:32    PLE1    R
189  2026-01-12 07:28:35    PLE1    R
190  2026-01-12 07:28:52    PLE1    R
191  2026-01-12 07:28:55    PLE1    R
192  2026-01-12 07:29:10    PLE1    R
193  2026-01-12 07:29:51    PLE1    R
194  2026-01-12 07:30:03    PLE1    R
195  2026-01-12 07:30:16    PLE1    R
196  2026-01-12 07:30:51    PLE1    R
197  2026-01-12 07:31:04    PLE1    R
198  2026-01-12 07:31:09    PLE1    R
199  2026-01-12 07:31:19    PLE1    R
200  2026-01-12 07:31:34    PLE1    R
201  2026-01-12 07:31:42    PLE1    R
202  2026-01-12 07:31:47    PLE1    R
203  2026-01-12 07:31:54    PLE1    R
204  2026-01-12 07:32:47    PLE1    R
205  2026-01-12 07:32:57    PLE1    R
206  2026-01-12 07:33:05    PLE1    R
207  2026-01-12 07:33:12    PLE1    R
208  2026-01-12 08:13:36    PLE1    R
209  2026-01-12 08:27:14    PLE1    R
210  2026-01-12 08:27:29    PLE1    R
211  2026-01-12 08:27:39    PLE1    R
212  2026-01-12 08:27:55    PLE1    R
213  2026-01-12 08:28:02    PLE1    R
214  2026-01-12 08:29:46    PLE1    R
215  2026-01-12 08:29:51    PLE1    R
216  2026-01-12 08:30:06    PLE1    R
217  2026-01-12 08:30:16    PLE1    R
218  2026-01-12 08:30:19    PLE1    R
219  2026-01-12 08:31:37    PLE1    R
220  2026-01-12 08:31:52    PLE1    R
221  2026-01-12 08:31:59    PLE1    R
222  2026-01-12 08:32:02    PLE1    R
223  2026-01-12 08:32:22    PLE1    R
224  2026-01-12 08:32:35    PLE1    R
225  2026-01-12 08:33:05    PLE1    R
226  2026-01-12 08:33:10    PLE1    R
227  2026-01-12 08:36:19    PLE1    R
228  2026-01-12 08:36:32    PLE1    R
229  2026-01-12 08:36:42    PLE1    R
230  2026-01-12 08:36:47    PLE1    R
231  2026-01-12 08:37:55    PLE1    R
232  2026-01-12 08:38:08    PLE1    R
233  2026-01-12 08:38:13    PLE1    R
234  2026-01-12 08:38:28    PLE1    R
235  2026-01-12 08:38:41    PLE1    R
236  2026-01-12 08:38:48    PLE1    R
237  2026-01-12 08:45:42    PLE1    R
238  2026-01-12 08:45:55    PLE1    R
239  2026-01-12 08:47:29    PLE1    R
240  2026-01-12 08:47:34    PLE1    R
241  2026-01-12 08:47:39    PLE1    R
242  2026-01-12 08:49:20    PLE1    R
243  2026-01-12 08:49:25    PLE1    R
244  2026-01-12 08:49:42    PLE1    R
245  2026-01-12 08:49:48    PLE1    R
246  2026-01-12 08:50:00    PLE1    R
247  2026-01-12 08:50:03    PLE1    R
248  2026-01-12 08:51:36    PLE1    R
249  2026-01-12 08:51:51    PLE1    R
250  2026-01-12 08:52:06    PLE1    R
251  2026-01-12 08:52:16    PLE1    R
252  2026-01-12 08:52:32    PLE1    R
253  2026-01-12 08:53:09    PLE1    R
254  2026-01-12 08:53:17    PLE1    R
255  2026-01-12 08:53:32    PLE1    R
256  2026-01-12 08:53:35    PLE1    R
257  2026-01-12 08:56:59    PLE1    R
258  2026-01-12 08:57:17    PLE1    R
259  2026-01-12 08:57:22    PLE1    R
260  2026-01-12 08:59:21    PLE1    R
261  2026-01-12 08:59:38    PLE1    R
262  2026-01-12 09:00:09    PLE1    R
263  2026-01-12 09:00:24    PLE1    R
264  2026-01-12 09:00:44    PLE1    R
265  2026-01-12 09:01:35    PLE1    R
266  2026-01-12 09:01:47    PLE1    R
267  2026-01-12 09:02:00    PLE1    R
268  2026-01-12 09:02:13    PLE1    R
269  2026-01-12 09:02:30    PLE1    R
270  2026-01-12 09:04:21    PLE1    R
271  2026-01-12 09:04:29    PLE1    R
272  2026-01-12 09:04:52    PLE1    R
273  2026-01-12 09:04:59    PLE1    R
274  2026-01-12 09:05:02    PLE1    R
275  2026-01-12 09:08:16    PLE1    R
276  2026-01-12 09:08:37    PLE1    R
277  2026-01-12 09:08:59    PLE1    R
278  2026-01-12 09:09:04    PLE1    R
279  2026-01-12 09:10:18    PLE1    R
280  2026-01-12 09:10:30    PLE1    R
281  2026-01-12 09:10:38    PLE1    R
282  2026-01-12 09:10:50    PLE1    R
283  2026-01-12 09:11:11    PLE1    R
284  2026-01-12 09:11:18    PLE1    R
285  2026-01-12 09:11:28    PLE1    R
286  2026-01-12 09:11:36    PLE1    R
287  2026-01-12 09:14:40    PLE1    R
288  2026-01-12 09:15:10    PLE1    R
289  2026-01-12 09:15:20    PLE1    R
290  2026-01-12 09:17:09    PLE1    R
291  2026-01-12 09:17:17    PLE1    R
292  2026-01-12 09:17:32    PLE1    R
293  2026-01-12 09:17:44    PLE1    R
294  2026-01-12 09:17:49    PLE1    R
295  2026-01-12 09:20:06    PLE1    R
296  2026-01-12 09:20:18    PLE1    R
297  2026-01-12 09:20:23    PLE1    R
298  2026-01-12 09:20:34    PLE1    R
299  2026-01-12 09:20:36    PLE1    R
300  2026-01-12 09:21:24    PLE1    R
301  2026-01-12 09:21:32    PLE1    R
302  2026-01-12 09:21:39    PLE1    R
303  2026-01-12 09:21:42    PLE1    R
304  2026-01-12 09:21:59    PLE1    R
305  2026-01-12 09:22:04    PLE1    R
306  2026-01-12 09:22:47    PLE1    R
307  2026-01-12 09:22:57    PLE1    R
308  2026-01-12 09:23:03    PLE1    R
309  2026-01-12 09:24:03    PLE1    R
310  2026-01-12 09:24:13    PLE1    R
311  2026-01-12 09:24:28    PLE1    R
312  2026-01-12 09:24:36    PLE1    R
313  2026-01-12 09:25:44    PLE1    R
314  2026-01-12 09:25:49    PLE1    R
315  2026-01-12 09:25:52    PLE1    R
316  2026-01-12 09:39:10    PLE1    R
317  2026-01-12 09:39:27    PLE1    R
318  2026-01-12 09:39:45    PLE1    R
319  2026-01-12 09:39:52    PLE1    R
320  2026-01-12 09:40:25    PLE1    R
321  2026-01-12 09:40:30    PLE1    R
322  2026-01-12 09:40:35    PLE1    R
323  2026-01-12 09:40:40    PLE1    R
324  2026-01-12 09:40:45    PLE1    R
325  2026-01-12 09:42:21    PLE1    R
326  2026-01-12 09:42:32    PLE1    R
327  2026-01-12 09:42:34    PLE1    R
328  2026-01-12 09:42:49    PLE1    R
329  2026-01-12 09:42:52    PLE1    R
330  2026-01-12 09:44:25    PLE1    R
331  2026-01-12 09:44:35    PLE1    R
332  2026-01-12 09:44:38    PLE1    R
333  2026-01-12 09:44:45    PLE1    R
334  2026-01-12 09:45:03    PLE1    R
335  2026-01-12 09:45:23    PLE1    R
336  2026-01-12 09:45:38    PLE1    R
337  2026-01-12 09:52:02    PLE1    R
338  2026-01-12 09:52:20    PLE1    R
339  2026-01-12 09:52:23    PLE1    R
340  2026-01-12 09:52:40    PLE1    R
341  2026-01-12 09:52:50    PLE1    R
342  2026-01-12 09:52:55    PLE1    R
343  2026-01-12 09:53:11    PLE1    R
344  2026-01-12 09:53:13    PLE1    R
345  2026-01-12 09:54:54    PLE1    R
346  2026-01-12 09:55:09    PLE1    R
347  2026-01-12 09:55:27    PLE1    R
348  2026-01-12 09:56:45    PLE1    R
349  2026-01-12 09:56:50    PLE1    R
350  2026-01-12 09:56:58    PLE1    R
351  2026-01-12 09:57:03    PLE1    R
352  2026-01-12 09:58:01    PLE1    R
353  2026-01-12 09:58:03    PLE1    R
354  2026-01-12 09:58:14    PLE1    R
355  2026-01-12 09:58:19    PLE1    R
356  2026-01-12 10:00:02    PLE1    R
357  2026-01-12 10:00:25    PLE1    R
358  2026-01-12 10:00:32    PLE1    R
359  2026-01-12 10:02:11    PLE1    R
360  2026-01-12 10:02:36    PLE1    R
361  2026-01-12 10:02:41    PLE1    R
362  2026-01-12 10:02:49    PLE1    R
363  2026-01-12 10:03:21    PLE1    R
364  2026-01-12 10:03:42    PLE1    R
365  2026-01-12 10:03:57    PLE1    R
366  2026-01-12 10:09:53    PLE1    R
367  2026-01-12 10:10:03    PLE1    R
368  2026-01-12 10:10:08    PLE1    R
369  2026-01-12 10:10:11    PLE1    R
370  2026-01-12 10:10:26    PLE1    R
371  2026-01-12 10:10:51    PLE1    R
372  2026-01-12 10:11:11    PLE1    R
373  2026-01-12 10:11:29    PLE1    R
374  2026-01-12 10:12:09    PLE1    R
375  2026-01-12 10:12:14    PLE1    R
376  2026-01-12 10:12:25    PLE1    R
377  2026-01-12 10:12:32    PLE1    R
378  2026-01-12 10:12:37    PLE1    R
379  2026-01-12 10:12:42    PLE1    R
380  2026-01-12 10:12:52    PLE1    R
381  2026-01-12 10:12:57    PLE1    R
382  2026-01-12 10:13:05    PLE1    R
383  2026-01-12 10:14:33    PLE1    R
384  2026-01-12 10:14:43    PLE1    R
385  2026-01-12 10:14:53    PLE1    R
386  2026-01-12 10:15:06    PLE1    R
387  2026-01-12 10:15:19    PLE1    R
388  2026-01-12 10:18:56    PLE1    R
389  2026-01-12 10:19:01    PLE1    R
390  2026-01-12 10:19:11    PLE1    R
391  2026-01-12 10:19:31    PLE1    R
392  2026-01-12 10:19:41    PLE1    R
393  2026-01-12 10:20:44    PLE1    R
394  2026-01-12 10:20:55    PLE1    R
395  2026-01-12 10:21:02    PLE1    R
396  2026-01-12 10:22:28    PLE1    R
397  2026-01-12 10:25:58    PLE1    R
398  2026-01-12 10:26:28    PLE1    R
399  2026-01-12 10:26:48    PLE1    R
400  2026-01-12 10:28:16    PLE1    R
401  2026-01-12 10:28:31    PLE1    R
402  2026-01-12 10:28:42    PLE1    R
403  2026-01-12 10:28:47    PLE1    R
404  2026-01-12 10:28:49    PLE1    R
405  2026-01-12 10:31:33    PLE1    R
406  2026-01-12 10:31:43    PLE1    R
407  2026-01-12 10:31:53    PLE1    R
408  2026-01-12 10:31:58    PLE1    R
409  2026-01-12 10:32:14    PLE1    R
410  2026-01-12 10:32:16    PLE1    R
411  2026-01-12 10:32:24    PLE1    R
412  2026-01-12 10:32:51    PLE1    R
413  2026-01-12 10:32:54    PLE1    R
414  2026-01-12 10:32:57    PLE1    R
415  2026-01-12 10:33:02    PLE1    R
416  2026-01-12 10:33:19    PLE1    R
417  2026-01-12 10:33:50    PLE1    R
418  2026-01-12 10:33:57    PLE1    R
419  2026-01-12 10:34:07    PLE1    R
420  2026-01-12 10:34:17    PLE1    R
421  2026-01-12 10:34:30    PLE1    R
422  2026-01-12 10:34:50    PLE1    R
423  2026-01-12 10:35:00    PLE1    R
424  2026-01-12 10:35:10    PLE1    R
425  2026-01-12 10:35:15    PLE1    R
426  2026-01-12 10:35:23    PLE1    R
427  2026-01-12 10:35:28    PLE1    R
428  2026-01-12 10:35:33    PLE1    R
429  2026-01-12 10:35:41    PLE1    R
430  2026-01-12 11:04:10    PLE1    R
431  2026-01-12 11:04:25    PLE1    R
432  2026-01-12 11:04:30    PLE1    R
433  2026-01-12 11:12:15    PLE1    R
434  2026-01-12 11:12:22    PLE1    R
435  2026-01-12 11:17:03    PLE1    R
436  2026-01-12 11:17:08    PLE1    R
437  2026-01-12 11:17:38    PLE1    R
438  2026-01-12 11:17:40    PLE1    R
439  2026-01-12 11:17:48    PLE1    R
440  2026-01-12 11:17:50    PLE1    R
441  2026-01-12 11:18:13    PLE1    R
442  2026-01-12 11:18:18    PLE1    R
443  2026-01-12 11:18:26    PLE1    R
444  2026-01-12 11:18:31    PLE1    R
445  2026-01-12 11:18:36    PLE1    R
446  2026-01-12 11:18:41    PLE1    R
447  2026-01-12 11:19:42    PLE1    R
448  2026-01-12 11:19:52    PLE1    R
449  2026-01-12 11:20:12    PLE1    R
450  2026-01-12 11:20:27    PLE1    R
451  2026-01-12 11:20:30    PLE1    R
452  2026-01-12 11:20:50    PLE1    R
453  2026-01-12 11:20:57    PLE1    R
454  2026-01-12 11:21:02    PLE1    R
455  2026-01-12 11:26:05    PLE1    R
456  2026-01-12 11:26:10    PLE1    R
457  2026-01-12 11:26:15    PLE1    R
458  2026-01-12 11:26:33    PLE1    R
459  2026-01-12 11:26:46    PLE1    R
460  2026-01-12 11:26:51    PLE1    R
461  2026-01-12 11:26:53    PLE1    R
462  2026-01-12 11:27:03    PLE1    R
463  2026-01-12 11:27:08    PLE1    R
464  2026-01-12 11:27:24    PLE1    R
465  2026-01-12 11:27:36    PLE1    R
466  2026-01-12 11:27:46    PLE1    R
467  2026-01-12 11:29:20    PLE1    R
468  2026-01-12 11:31:06    PLE1    R
469  2026-01-12 11:31:21    PLE1    R
470  2026-01-12 11:32:11    PLE1    R
471  2026-01-12 11:32:14    PLE1    R
472  2026-01-12 11:32:19    PLE1    R
473  2026-01-12 11:32:39    PLE1    R
474  2026-01-12 11:32:42    PLE1    R
475  2026-01-12 11:32:49    PLE1    R
476  2026-01-12 11:32:54    PLE1    R
477  2026-01-12 11:48:06    PLE1    R
478  2026-01-12 11:48:16    PLE1    R
479  2026-01-12 11:49:12    PLE1    R
480  2026-01-12 11:49:32    PLE1    R
481  2026-01-12 11:49:37    PLE1    R
482  2026-01-12 11:49:40    PLE1    R
483  2026-01-12 11:49:45    PLE1    R
484  2026-01-12 11:50:02    PLE1    R
485  2026-01-12 11:50:33    PLE1    R
486  2026-01-12 11:51:38    PLE1    R
487  2026-01-12 11:51:43    PLE1    R
488  2026-01-12 11:51:48    PLE1    R
489  2026-01-12 11:52:14    PLE1    R
490  2026-01-12 11:52:19    PLE1    R
491  2026-01-12 11:53:57    PLE1    R
492  2026-01-12 11:54:05    PLE1    R
493  2026-01-12 11:54:12    PLE1    R
494  2026-01-12 11:54:22    PLE1    R
495  2026-01-12 11:54:27    PLE1    R
496  2026-01-12 11:54:37    PLE1    R
497  2026-01-12 11:54:43    PLE1    R
498  2026-01-12 12:44:37    PLE1    R
499  2026-01-12 12:44:44    PLE1    R
500  2026-01-12 12:44:47    PLE1    R
501  2026-01-12 12:45:02    PLE1    R
502  2026-01-12 12:45:15    PLE1    R
503  2026-01-12 12:47:16    PLE1    R
504  2026-01-12 12:47:23    PLE1    R
505  2026-01-12 12:47:31    PLE1    R
506  2026-01-12 12:47:36    PLE1    R
507  2026-01-12 12:47:39    PLE1    R
508  2026-01-12 12:47:54    PLE1    R
509  2026-01-12 12:48:04    PLE1    R
510  2026-01-12 12:48:06    PLE1    R
511  2026-01-12 12:48:16    PLE1    R
512  2026-01-12 12:48:19    PLE1    R
513  2026-01-12 12:48:34    PLE1    R
514  2026-01-12 12:48:39    PLE1    R
515  2026-01-12 12:48:47    PLE1    R
516  2026-01-12 12:49:57    PLE1    R
517  2026-01-12 12:50:13    PLE1    R
518  2026-01-12 12:50:20    PLE1    R
519  2026-01-12 12:50:33    PLE1    R
520  2026-01-12 12:50:43    PLE1    R
521  2026-01-12 12:51:31    PLE1    R
522  2026-01-12 12:51:41    PLE1    R
523  2026-01-12 12:51:48    PLE1    R
524  2026-01-12 12:51:51    PLE1    R

In [ ]:
# Funcion detectar_fin_evetos

def detectar_fin_por_retorno(df_signal, t_ini, baseline, tol, t_estable):
    """
    df_signal: DataFrame con columnas ['temporal_placa', 'corriente']
    t_ini: timestamp desde donde buscar el fin
    baseline: valor medio de corriente
    tol: tolerancia absoluta
    """
    df_post = df_signal[df_signal['temporal_placa'] >= t_ini].copy()

    df_post['en_regimen'] = (
        (df_post['corriente'] >= baseline - tol) &
        (df_post['corriente'] <= baseline + tol)
    )

    # detectar permanencia continua
    df_post['dt'] = df_post['temporal_placa'].diff()
    df_post['grupo'] = (
        (~df_post['en_regimen']) |
        (df_post['dt'] > df_post['dt'].median() * 2)
    ).cumsum()

    for _, g in df_post.groupby('grupo'):
        if g['en_regimen'].all():
            dur = g['temporal_placa'].iloc[-1] - g['temporal_placa'].iloc[0]
            if dur >= t_estable:
                return g['temporal_placa'].iloc[0]

    return None

In [ ]:
# Analisis de eventos

import pandas as pd

# =================================================
# 1) PREPROCESAR SEÑALES
# =================================================

signal_dict = {}

df_all_ple1 = df_all[df_all['maquina'] == maq_obj].copy()

df_all_ple1['temporal_placa'] = (
    pd.to_datetime(df_all_ple1['temporal_placa'])
    .dt.tz_localize(None)
)

for fase in FASES:
    col = f'corriente_{fase.lower()}'
    signal_dict[fase] = (
        df_all_ple1[['temporal_placa', col]]
        .rename(columns={col: 'corriente'})
        .sort_values('temporal_placa')
        .reset_index(drop=True)
    )

# =================================================
# 2) BASELINE POR FASE (ROBUSTO)
# =================================================

baseline_fase = (
    medias_por_fase
    .set_index('fase')['baseline']
    .to_dict()
)

# =================================================
# 3) PICOS DE LA MAQUINA
# =================================================

df_peaks = df_peaks_all[
    df_peaks_all['maquina'] == maq_obj
].copy()

df_peaks['temporal_placa'] = (
    pd.to_datetime(df_peaks['temporal_placa'])
    .dt.tz_localize(None)
)

# =================================================
# 4) DETECCION DE EVENTOS (SIN SOLAPES)
# =================================================

rows = []

for fase in FASES:

    fase = str(fase).upper().strip()

    if fase not in baseline_fase:
        continue

    baseline = baseline_fase[fase]
    tol = baseline * tol_pct

    df_signal = signal_dict[fase]

    df_peaks_fase = (
        df_peaks[df_peaks['fase'].str.upper() == fase]
        .sort_values('temporal_placa')
        .reset_index(drop=True)
    )

    if df_peaks_fase.empty:
        continue

    # lookup rápido de picos
    picos_set = set(df_peaks_fase['temporal_placa'])

    # ---------------------------
    # ESTADOS
    # ---------------------------
    regimen_confirmado = False
    t_regimen_inicio_global = None

    evento_activo = False
    evento_id = 0
    fecha_inicio = None

    t_regimen_inicio = None

    # =================================================
    # LOOP SOBRE LA SEÑAL CONTINUA
    # =================================================
    for i in range(len(df_signal)):

        t = df_signal.loc[i, 'temporal_placa']
        corriente = df_signal.loc[i, 'corriente']

        hay_pico = t in picos_set
        en_regimen = (baseline - tol <= corriente <= baseline + tol)

        # ------------------------------------------------
        # 4.1 WARM-UP: confirmar régimen inicial
        # ------------------------------------------------
        if not regimen_confirmado:
            if en_regimen:
                if t_regimen_inicio_global is None:
                    t_regimen_inicio_global = t
                elif t - t_regimen_inicio_global >= t_estable:
                    regimen_confirmado = True
            else:
                t_regimen_inicio_global = None
            continue

        # ------------------------------------------------
        # 4.2 INICIO DE EVENTO
        # ------------------------------------------------
        if not evento_activo:
            if hay_pico:
                evento_activo = True
                evento_id += 1
                fecha_inicio = t
                t_regimen_inicio = None
            continue

        # ------------------------------------------------
        # 4.3 EVENTO ACTIVO
        # ------------------------------------------------
        if not en_regimen:
            # fuera de régimen → sigue evento
            t_regimen_inicio = None
            continue

        if hay_pico:
            # pico mientras vuelve → no puede cerrar
            t_regimen_inicio = None
            continue

        # en régimen, sin pico
        if t_regimen_inicio is None:
            t_regimen_inicio = t
        elif t - t_regimen_inicio >= t_estable:
            # FIN REAL DEL EVENTO
            rows.append({
                'maquina': maq_obj,
                'fase': fase,
                'ID_Evento': evento_id,
                'Fecha Inicio': fecha_inicio,
                'Fecha Fin': t_regimen_inicio,
                'Duracion Evento': t_regimen_inicio - fecha_inicio
            })
            evento_activo = False
            fecha_inicio = None
            t_regimen_inicio = None

    # ------------------------------------------------
    # EVENTO ABIERTO SIN CIERRE (final del dataset)
    # ------------------------------------------------
    if evento_activo and fecha_inicio is not None:
        t_fin = df_signal.iloc[-1]['temporal_placa']
        rows.append({
            'maquina': maq_obj,
            'fase': fase,
            'ID_Evento': evento_id,
            'Fecha Inicio': fecha_inicio,
            'Fecha Fin': t_fin,
            'Duracion Evento': t_fin - fecha_inicio
        })

# =================================================
# 5) DATAFRAME FINAL
# =================================================

df_evento = (
    pd.DataFrame(rows)
    .sort_values(by=['fase', 'ID_Evento'])
    .reset_index(drop=True)
)

df_evento

,maquina,fase,ID_Evento,Fecha Inicio,Fecha Fin,Duracion Evento
0,PLE1,R,1,2026-01-12 05:20:18,2026-01-12 05:21:09,0 days 00:00:51
1,PLE1,R,2,2026-01-12 05:23:30,2026-01-12 05:24:11,0 days 00:00:41
2,PLE1,R,3,2026-01-12 05:26:55,2026-01-12 05:27:23,0 days 00:00:28
3,PLE1,R,4,2026-01-12 05:30:55,2026-01-12 05:32:18,0 days 00:01:23
4,PLE1,R,5,2026-01-12 05:35:52,2026-01-12 05:36:30,0 days 00:00:38
5,PLE1,R,6,2026-01-12 05:40:25,2026-01-12 05:40:58,0 days 00:00:33
6,PLE1,R,7,2026-01-12 05:45:16,2026-01-12 05:45:48,0 days 00:00:32
7,PLE1,R,8,2026-01-12 05:47:52,2026-01-12 05:48:22,0 days 00:00:30
8,PLE1,R,9,2026-01-12 05:50:34,2026-01-12 05:50:36,0 days 00:00:02
9,PLE1,R,10,2026-01-12 05:50:51,2026-01-12 05:51:17,0 days 00:00:26
10,PLE1,R,11,2026-01-12 05:51:37,2026-01-12 05:52:30,0 days 00:00:53
11,PLE1,R,12,2026-01-12 05:54:13,2026-01-12 05:55:09,0 days 00:00:56
12,PLE1,R,13,2026-01-12 05:55:21,2026-01-12 05:56:17,0 days 00:00:56
13,PLE1,R,14,2026-01-12 06:02:06,2026-01-12 06:02:28,0 days 00:00:22
14,PLE1,R,15,2026-01-12 06:06:16,2026-01-12 06:07:19,0 days 00:01:03
15,PLE1,R,16,2026-01-12 06:08:12,2026-01-12 06:08:34,0 days 00:00:22
16,PLE1,R,17,2026-01-12 06:11:31,2026-01-12 06:12:09,0 days 00:00:38
17,PLE1,R,18,2026-01-12 06:13:52,2026-01-12 06:13:55,0 days 00:00:03
18,PLE1,R,19,2026-01-12 06:14:08,2026-01-12 06:14:15,0 days 00:00:07
19,PLE1,R,20,2026-01-12 06:17:50,2026-01-12 06:18:13,0 days 00:00:23
20,PLE1,R,21,2026-01-12 06:18:35,2026-01-12 06:18:50,0 days 00:00:15
21,PLE1,R,22,2026-01-12 06:20:16,2026-01-12 06:20:47,0 days 00:00:31
22,PLE1,R,23,2026-01-12 06:22:38,2026-01-12 06:23:38,0 days 00:01:00
23,PLE1,R,24,2026-01-12 06:23:58,2026-01-12 06:25:45,0 days 00:01:47
24,PLE1,R,25,2026-01-12 06:26:17,2026-01-12 06:26:45,0 days 00:00:28
25,PLE1,R,26,2026-01-12 06:39:58,2026-01-12 06:40:48,0 days 00:00:50
26,PLE1,R,27,2026-01-12 06:42:40,2026-01-12 06:43:25,0 days 00:00:45
27,PLE1,R,28,2026-01-12 06:44:43,2026-01-12 06:44:58,0 days 00:00:15
28,PLE1,R,29,2026-01-12 06:45:16,2026-01-12 06:46:29,0 days 00:01:13
29,PLE1,R,30,2026-01-12 06:48:28,2026-01-12 06:50:01,0 days 00:01:33
30,PLE1,R,31,2026-01-12 06:50:16,2026-01-12 06:51:27,0 days 00:01:11
31,PLE1,R,32,2026-01-12 06:52:53,2026-01-12 06:53:13,0 days 00:00:20
32,PLE1,R,33,2026-01-12 06:54:54,2026-01-12 06:55:37,0 days 00:00:43
33,PLE1,R,34,2026-01-12 06:57:08,2026-01-12 06:57:41,0 days 00:00:33
34,PLE1,R,35,2026-01-12 06:58:04,2026-01-12 06:58:47,0 days 00:00:43
35,PLE1,R,36,2026-01-12 06:59:14,2026-01-12 06:59:37,0 days 00:00:23
36,PLE1,R,37,2026-01-12 07:01:08,2026-01-12 07:02:57,0 days 00:01:49
37,PLE1,R,38,2026-01-12 07:07:32,2026-01-12 07:07:57,0 days 00:00:25
38,PLE1,R,39,2026-01-12 07:10:39,2026-01-12 07:11:09,0 days 00:00:30
39,PLE1,R,40,2026-01-12 07:11:34,2026-01-12 07:12:30,0 days 00:00:56
40,PLE1,R,41,2026-01-12 07:14:11,2026-01-12 07:14:31,0 days 00:00:20
41,PLE1,R,42,2026-01-12 07:14:44,2026-01-12 07:14:46,0 days 00:00:02
42,PLE1,R,43,2026-01-12 07:19:37,2026-01-12 07:19:47,0 days 00:00:10
43,PLE1,R,44,2026-01-12 07:20:12,2026-01-12 07:20:15,0 days 00:00:03
44,PLE1,R,45,2026-01-12 07:20:27,2026-01-12 07:20:32,0 days 00:00:05
45,PLE1,R,46,2026-01-12 07:21:18,2026-01-12 07:21:58,0 days 00:00:40
46,PLE1,R,47,2026-01-12 07:26:08,2026-01-12 07:26:34,0 days 00:00:26
47,PLE1,R,48,2026-01-12 07:27:47,2026-01-12 07:28:40,0 days 00:00:53
48,PLE1,R,49,2026-01-12 07:28:52,2026-01-12 07:28:58,0 days 00:00:06
49,PLE1,R,50,2026-01-12 07:29:10,2026-01-12 07:29:13,0 days 00:00:03
50,PLE1,R,51,2026-01-12 07:29:51,2026-01-12 07:31:57,0 days 00:02:06
51,PLE1,R,52,2026-01-12 07:32:47,2026-01-12 07:33:15,0 days 00:00:28
52,PLE1,R,53,2026-01-12 08:13:36,2026-01-12 08:13:39,0 days 00:00:03
53,PLE1,R,54,2026-01-12 08:27:14,2026-01-12 08:28:07,0 days 00:00:53
54,PLE1,R,55,2026-01-12 08:29:46,2026-01-12 08:30:24,0 days 00:00:38
55,PLE1,R,56,2026-01-12 08:31:37,2026-01-12 08:32:04,0 days 00:00:27
56,PLE1,R,57,2026-01-12 08:32:22,2026-01-12 08:33:15,0 days 00:00:53
57,PLE1,R,58,2026-01-12 08:36:19,2026-01-12 08:36:50,0 days 00:00:31
58,PLE1,R,59,2026-01-12 08:37:55,2026-01-12 08:38:51,0 days 00:00:56
59,PLE1,R,60,2026-01-12 08:45:42,2026-01-12 08:46:00,0 days 00:00:18
60,PLE1,R,61,2026-01-12 08:47:29,2026-01-12 08:47:44,0 days 00:00:15
61,PLE1,R,62,2026-01-12 08:49:20,2026-01-12 08:50:05,0 days 00:00:45
62,PLE1,R,63,2026-01-12 08:51:36,2026-01-12 08:52:34,0 days 00:00:58
63,PLE1,R,64,2026-01-12 08:53:09,2026-01-12 08:53:40,0 days 00:00:31
64,PLE1,R,65,2026-01-12 08:56:59,2026-01-12 08:57:27,0 days 00:00:28
65,PLE1,R,66,2026-01-12 08:59:21,2026-01-12 08:59:41,0 days 00:00:20
66,PLE1,R,67,2026-01-12 09:00:09,2026-01-12 09:00:49,0 days 00:00:40
67,PLE1,R,68,2026-01-12 09:01:35,2026-01-12 09:02:15,0 days 00:00:40
68,PLE1,R,69,2026-01-12 09:02:30,2026-01-12 09:02:35,0 days 00:00:05
69,PLE1,R,70,2026-01-12 09:04:21,2026-01-12 09:05:07,0 days 00:00:46
70,PLE1,R,71,2026-01-12 09:08:16,2026-01-12 09:09:09,0 days 00:00:53
71,PLE1,R,72,2026-01-12 09:10:18,2026-01-12 09:10:53,0 days 00:00:35
72,PLE1,R,73,2026-01-12 09:11:11,2026-01-12 09:11:48,0 days 00:00:37
73,PLE1,R,74,2026-01-12 09:14:40,2026-01-12 09:14:48,0 days 00:00:08
74,PLE1,R,75,2026-01-12 09:15:10,2026-01-12 09:15:26,0 days 00:00:16
75,PLE1,R,76,2026-01-12 09:17:09,2026-01-12 09:17:55,0 days 00:00:46
76,PLE1,R,77,2026-01-12 09:20:06,2026-01-12 09:20:39,0 days 00:00:33
77,PLE1,R,78,2026-01-12 09:21:24,2026-01-12 09:21:47,0 days 00:00:23
78,PLE1,R,79,2026-01-12 09:21:59,2026-01-12 09:22:07,0 days 00:00:08
79,PLE1,R,80,2026-01-12 09:22:47,2026-01-12 09:23:08,0 days 00:00:21
80,PLE1,R,81,2026-01-12 09:24:03,2026-01-12 09:24:38,0 days 00:00:35
81,PLE1,R,82,2026-01-12 09:25:44,2026-01-12 09:25:57,0 days 00:00:13
82,PLE1,R,83,2026-01-12 09:39:10,2026-01-12 09:39:12,0 days 00:00:02
83,PLE1,R,84,2026-01-12 09:39:27,2026-01-12 09:39:55,0 days 00:00:28
84,PLE1,R,85,2026-01-12 09:40:25,2026-01-12 09:40:48,0 days 00:00:23
85,PLE1,R,86,2026-01-12 09:42:21,2026-01-12 09:42:54,0 days 00:00:33
86,PLE1,R,87,2026-01-12 09:44:25,2026-01-12 09:44:48,0 days 00:00:23
87,PLE1,R,88,2026-01-12 09:45:03,2026-01-12 09:45:26,0 days 00:00:23
88,PLE1,R,89,2026-01-12 09:45:38,2026-01-12 09:45:44,0 days 00:00:06
89,PLE1,R,90,2026-01-12 09:52:02,2026-01-12 09:52:25,0 days 00:00:23
90,PLE1,R,91,2026-01-12 09:52:40,2026-01-12 09:53:16,0 days 00:00:36
91,PLE1,R,92,2026-01-12 09:54:54,2026-01-12 09:55:29,0 days 00:00:35
92,PLE1,R,93,2026-01-12 09:56:45,2026-01-12 09:57:05,0 days 00:00:20
93,PLE1,R,94,2026-01-12 09:58:01,2026-01-12 09:58:21,0 days 00:00:20
94,PLE1,R,95,2026-01-12 10:00:02,2026-01-12 10:00:35,0 days 00:00:33
95,PLE1,R,96,2026-01-12 10:02:11,2026-01-12 10:02:51,0 days 00:00:40
96,PLE1,R,97,2026-01-12 10:03:21,2026-01-12 10:04:07,0 days 00:00:46
97,PLE1,R,98,2026-01-12 10:09:53,2026-01-12 10:10:28,0 days 00:00:35
98,PLE1,R,99,2026-01-12 10:10:51,2026-01-12 10:11:32,0 days 00:00:41
99,PLE1,R,100,2026-01-12 10:12:09,2026-01-12 10:13:07,0 days 00:00:58
100,PLE1,R,101,2026-01-12 10:14:33,2026-01-12 10:15:24,0 days 00:00:51
101,PLE1,R,102,2026-01-12 10:18:56,2026-01-12 10:19:14,0 days 00:00:18
102,PLE1,R,103,2026-01-12 10:19:31,2026-01-12 10:19:44,0 days 00:00:13
103,PLE1,R,104,2026-01-12 10:20:44,2026-01-12 10:21:05,0 days 00:00:21
104,PLE1,R,105,2026-01-12 10:22:28,2026-01-12 10:22:36,0 days 00:00:08
105,PLE1,R,106,2026-01-12 10:25:58,2026-01-12 10:26:08,0 days 00:00:10
106,PLE1,R,107,2026-01-12 10:26:28,2026-01-12 10:26:50,0 days 00:00:22
107,PLE1,R,108,2026-01-12 10:28:16,2026-01-12 10:28:54,0 days 00:00:38
108,PLE1,R,109,2026-01-12 10:31:33,2026-01-12 10:32:29,0 days 00:00:56
109,PLE1,R,110,2026-01-12 10:32:51,2026-01-12 10:33:04,0 days 00:00:13
110,PLE1,R,111,2026-01-12 10:33:19,2026-01-12 10:34:35,0 days 00:01:16
111,PLE1,R,112,2026-01-12 10:34:50,2026-01-12 10:35:43,0 days 00:00:53
112,PLE1,R,113,2026-01-12 11:04:10,2026-01-12 11:05:03,0 days 00:00:53
113,PLE1,R,114,2026-01-12 11:12:15,2026-01-12 11:12:27,0 days 00:00:12
114,PLE1,R,115,2026-01-12 11:17:03,2026-01-12 11:17:13,0 days 00:00:10
115,PLE1,R,116,2026-01-12 11:17:38,2026-01-12 11:17:53,0 days 00:00:15
116,PLE1,R,117,2026-01-12 11:18:13,2026-01-12 11:18:43,0 days 00:00:30
117,PLE1,R,118,2026-01-12 11:19:42,2026-01-12 11:19:54,0 days 00:00:12
118,PLE1,R,119,2026-01-12 11:20:12,2026-01-12 11:20:32,0 days 00:00:20
119,PLE1,R,120,2026-01-12 11:20:50,2026-01-12 11:21:28,0 days 00:00:38
120,PLE1,R,121,2026-01-12 11:26:05,2026-01-12 11:27:49,0 days 00:01:44
121,PLE1,R,122,2026-01-12 11:29:20,2026-01-12 11:29:32,0 days 00:00:12
122,PLE1,R,123,2026-01-12 11:31:06,2026-01-12 11:31:23,0 days 00:00:17
123,PLE1,R,124,2026-01-12 11:32:11,2026-01-12 11:32:22,0 days 00:00:11
124,PLE1,R,125,2026-01-12 11:32:39,2026-01-12 11:32:57,0 days 00:00:18
125,PLE1,R,126,2026-01-12 11:48:06,2026-01-12 11:48:21,0 days 00:00:15
126,PLE1,R,127,2026-01-12 11:49:12,2026-01-12 11:50:12,0 days 00:01:00
127,PLE1,R,128,2026-01-12 11:50:33,2026-01-12 11:50:38,0 days 00:00:05
128,PLE1,R,129,2026-01-12 11:51:38,2026-01-12 11:52:26,0 days 00:00:48
129,PLE1,R,130,2026-01-12 11:53:57,2026-01-12 11:54:48,0 days 00:00:51
130,PLE1,R,131,2026-01-12 12:44:37,2026-01-12 12:44:49,0 days 00:00:12
131,PLE1,R,132,2026-01-12 12:45:02,2026-01-12 12:45:17,0 days 00:00:15
132,PLE1,R,133,2026-01-12 12:47:16,2026-01-12 12:47:41,0 days 00:00:25
133,PLE1,R,134,2026-01-12 12:47:54,2026-01-12 12:48:21,0 days 00:00:27
134,PLE1,R,135,2026-01-12 12:48:34,2026-01-12 12:48:49,0 days 00:00:15
135,PLE1,R,136,2026-01-12 12:49:57,2026-01-12 12:50:45,0 days 00:00:48
136,PLE1,R,137,2026-01-12 12:51:31,2026-01-12 12:52:11,0 days 00:00:40
137,PLE1,R,138,2026-01-12 12:52:24,2026-01-12 12:52:49,0 days 00:00:25
138,PLE1,R,139,2026-01-12 12:53:07,2026-01-12 12:53:45,0 days 00:00:38
139,PLE1,R,140,2026-01-12 12:54:05,2026-01-12 12:54:30,0 days 00:00:25
140,PLE1,R,141,2026-01-12 12:56:13,2026-01-12 12:56:29,0 days 00:00:16
141,PLE1,R,142,2026-01-12 12:56:56,2026-01-12 12:57:24,0 days 00:00:28
142,PLE1,R,143,2026-01-12 12:57:37,2026-01-12 12:58:07,0 days 00:00:30
143,PLE1,R,144,2026-01-12 12:58:22,2026-01-12 12:58:53,0 days 00:00:31
144,PLE1,R,145,2026-01-12 13:12:25,2026-01-12 13:12:58,0 days 00:00:33
145,PLE1,R,146,2026-01-12 13:16:13,2026-01-12 13:16:55,0 days 00:00:42
146,PLE1,R,147,2026-01-12 13:18:14,2026-01-12 13:18:57,0 days 00:00:43
147,PLE1,R,148,2026-01-12 13:19:17,2026-01-12 13:19:47,0 days 00:00:30
148,PLE1,R,149,2026-01-12 13:26:41,2026-01-12 13:26:59,0 days 00:00:18
149,PLE1,R,150,2026-01-12 13:38:56,2026-01-12 13:39:16,0 days 00:00:20
150,PLE1,R,151,2026-01-12 13:41:52,2026-01-12 13:42:33,0 days 00:00:41
151,PLE1,R,152,2026-01-12 13:42:48,2026-01-12 13:43:16,0 days 00:00:28
152,PLE1,R,153,2026-01-12 13:43:38,2026-01-12 13:44:19,0 days 00:00:41
153,PLE1,R,154,2026-01-12 13:44:41,2026-01-12 13:45:22,0 days 00:00:41
154,PLE1,R,155,2026-01-12 13:45:47,2026-01-12 13:46:25,0 days 00:00:38
155,PLE1,R,156,2026-01-12 13:46:45,2026-01-12 13:46:48,0 days 00:00:03
156,PLE1,R,157,2026-01-12 13:47:10,2026-01-12 13:50:10,0 days 00:03:00
157,PLE1,R,158,2026-01-12 13:57:57,2026-01-12 13:58:13,0 days 00:00:16
158,PLE1,R,159,2026-01-12 13:59:18,2026-01-12 14:00:24,0 days 00:01:06
159,PLE1,R,160,2026-01-12 14:00:52,2026-01-12 14:04:26,0 days 00:03:34
160,PLE1,R,161,2026-01-12 14:05:29,2026-01-12 14:05:50,0 days 00:00:21
161,PLE1,R,162,2026-01-12 14:18:37,2026-01-12 14:18:40,0 days 00:00:03
162,PLE1,R,163,2026-01-12 14:19:23,2026-01-12 14:20:03,0 days 00:00:40
163,PLE1,R,164,2026-01-12 14:21:11,2026-01-12 14:21:34,0 days 00:00:23
164,PLE1,R,165,2026-01-12 14:22:27,2026-01-12 14:22:50,0 days 00:00:23
165,PLE1,R,166,2026-01-12 14:24:36,2026-01-12 14:24:51,0 days 00:00:15
166,PLE1,R,167,2026-01-12 14:25:39,2026-01-12 14:25:54,0 days 00:00:15
167,PLE1,R,168,2026-01-12 14:28:08,2026-01-12 14:28:23,0 days 00:00:15
168,PLE1,R,169,2026-01-12 14:29:14,2026-01-12 14:29:29,0 days 00:00:15
169,PLE1,R,170,2026-01-12 14:30:27,2026-01-12 14:30:40,0 days 00:00:13
170,PLE1,R,171,2026-01-12 14:30:55,2026-01-12 14:31:35,0 days 00:00:40
171,PLE1,R,172,2026-01-12 14:32:51,2026-01-12 14:33:21,0 days 00:00:30
172,PLE1,R,173,2026-01-12 14:34:50,2026-01-12 14:36:25,0 days 00:01:35
173,PLE1,R,174,2026-01-12 14:38:57,2026-01-12 14:39:37,0 days 00:00:40
174,PLE1,R,175,2026-01-12 14:39:55,2026-01-12 14:40:28,0 days 00:00:33
175,PLE1,R,176,2026-01-12 14:40:41,2026-01-12 14:41:59,0 days 00:01:18
176,PLE1,R,177,2026-01-12 14:42:11,2026-01-12 14:42:44,0 days 00:00:33
177,PLE1,R,178,2026-01-12 14:43:07,2026-01-12 14:43:35,0 days 00:00:28
178,PLE1,R,179,2026-01-12 14:43:52,2026-01-12 14:45:13,0 days 00:01:21
179,PLE1,R,180,2026-01-12 14:47:09,2026-01-12 14:47:47,0 days 00:00:38
180,PLE1,R,181,2026-01-12 14:50:11,2026-01-12 15:04:07,0 days 00:13:56
181,PLE1,S,1,2026-01-12 05:20:18,2026-01-12 05:21:32,0 days 00:01:14
182,PLE1,S,2,2026-01-12 05:23:30,2026-01-12 05:27:43,0 days 00:04:13
183,PLE1,S,3,2026-01-12 05:30:55,2026-01-12 05:32:36,0 days 00:01:41
184,PLE1,S,4,2026-01-12 05:35:52,2026-01-12 05:36:46,0 days 00:00:54
185,PLE1,S,5,2026-01-12 05:40:25,2026-01-12 05:40:58,0 days 00:00:33
186,PLE1,S,6,2026-01-12 05:45:16,2026-01-12 05:45:48,0 days 00:00:32
187,PLE1,S,7,2026-01-12 05:47:52,2026-01-12 05:48:22,0 days 00:00:30
188,PLE1,S,8,2026-01-12 05:50:34,2026-01-12 05:50:36,0 days 00:00:02
189,PLE1,S,9,2026-01-12 05:50:51,2026-01-12 05:51:17,0 days 00:00:26
190,PLE1,S,10,2026-01-12 05:51:37,2026-01-12 05:52:30,0 days 00:00:53
191,PLE1,S,11,2026-01-12 05:54:13,2026-01-12 05:54:49,0 days 00:00:36
192,PLE1,S,12,2026-01-12 05:55:21,2026-01-12 05:56:17,0 days 00:00:56
193,PLE1,S,13,2026-01-12 06:02:06,2026-01-12 06:02:28,0 days 00:00:22
194,PLE1,S,14,2026-01-12 06:06:16,2026-01-12 06:06:26,0 days 00:00:10
195,PLE1,S,15,2026-01-12 06:06:53,2026-01-12 06:07:19,0 days 00:00:26
196,PLE1,S,16,2026-01-12 06:08:12,2026-01-12 06:08:34,0 days 00:00:22
197,PLE1,S,17,2026-01-12 06:11:31,2026-01-12 06:12:09,0 days 00:00:38
198,PLE1,S,18,2026-01-12 06:13:52,2026-01-12 06:13:55,0 days 00:00:03
199,PLE1,S,19,2026-01-12 06:14:08,2026-01-12 06:14:15,0 days 00:00:07
200,PLE1,S,20,2026-01-12 06:17:50,2026-01-12 06:18:10,0 days 00:00:20
201,PLE1,S,21,2026-01-12 06:18:35,2026-01-12 06:18:50,0 days 00:00:15
202,PLE1,S,22,2026-01-12 06:20:16,2026-01-12 06:20:49,0 days 00:00:33
203,PLE1,S,23,2026-01-12 06:22:38,2026-01-12 06:23:21,0 days 00:00:43
204,PLE1,S,24,2026-01-12 06:23:58,2026-01-12 06:24:16,0 days 00:00:18
205,PLE1,S,25,2026-01-12 06:24:29,2026-01-12 06:25:12,0 days 00:00:43
206,PLE1,S,26,2026-01-12 06:25:32,2026-01-12 06:25:45,0 days 00:00:13
207,PLE1,S,27,2026-01-12 06:26:17,2026-01-12 06:26:45,0 days 00:00:28
208,PLE1,S,28,2026-01-12 06:39:58,2026-01-12 06:40:48,0 days 00:00:50
209,PLE1,S,29,2026-01-12 06:42:40,2026-01-12 06:43:25,0 days 00:00:45
210,PLE1,S,30,2026-01-12 06:44:43,2026-01-12 06:44:58,0 days 00:00:15
211,PLE1,S,31,2026-01-12 06:45:16,2026-01-12 06:46:29,0 days 00:01:13
212,PLE1,S,32,2026-01-12 06:48:28,2026-01-12 06:48:30,0 days 00:00:02
213,PLE1,S,33,2026-01-12 06:49:23,2026-01-12 06:50:01,0 days 00:00:38
214,PLE1,S,34,2026-01-12 06:50:16,2026-01-12 06:51:27,0 days 00:01:11
215,PLE1,S,35,2026-01-12 06:52:53,2026-01-12 06:53:13,0 days 00:00:20
216,PLE1,S,36,2026-01-12 06:54:57,2026-01-12 06:55:37,0 days 00:00:40
217,PLE1,S,37,2026-01-12 06:57:11,2026-01-12 06:57:41,0 days 00:00:30
218,PLE1,S,38,2026-01-12 06:58:44,2026-01-12 06:58:47,0 days 00:00:03
219,PLE1,S,39,2026-01-12 06:59:14,2026-01-12 06:59:37,0 days 00:00:23
220,PLE1,S,40,2026-01-12 07:01:08,2026-01-12 07:01:28,0 days 00:00:20
221,PLE1,S,41,2026-01-12 07:02:19,2026-01-12 07:02:57,0 days 00:00:38
222,PLE1,S,42,2026-01-12 07:07:32,2026-01-12 07:07:57,0 days 00:00:25
223,PLE1,S,43,2026-01-12 07:10:39,2026-01-12 07:10:49,0 days 00:00:10
224,PLE1,S,44,2026-01-12 07:11:07,2026-01-12 07:11:09,0 days 00:00:02
225,PLE1,S,45,2026-01-12 07:11:34,2026-01-12 07:11:37,0 days 00:00:03
226,PLE1,S,46,2026-01-12 07:11:57,2026-01-12 07:12:27,0 days 00:00:30
227,PLE1,S,47,2026-01-12 07:14:11,2026-01-12 07:14:31,0 days 00:00:20
228,PLE1,S,48,2026-01-12 07:14:44,2026-01-12 07:14:46,0 days 00:00:02
229,PLE1,S,49,2026-01-12 07:19:37,2026-01-12 07:19:47,0 days 00:00:10
230,PLE1,S,50,2026-01-12 07:20:12,2026-01-12 07:20:15,0 days 00:00:03
231,PLE1,S,51,2026-01-12 07:20:27,2026-01-12 07:20:32,0 days 00:00:05
232,PLE1,S,52,2026-01-12 07:21:18,2026-01-12 07:21:58,0 days 00:00:40
233,PLE1,S,53,2026-01-12 07:26:08,2026-01-12 07:26:34,0 days 00:00:26
234,PLE1,S,54,2026-01-12 07:27:47,2026-01-12 07:28:40,0 days 00:00:53
235,PLE1,S,55,2026-01-12 07:28:52,2026-01-12 07:28:58,0 days 00:00:06
236,PLE1,S,56,2026-01-12 07:29:10,2026-01-12 07:29:13,0 days 00:00:03
237,PLE1,S,57,2026-01-12 07:29:51,2026-01-12 07:30:38,0 days 00:00:47
238,PLE1,S,58,2026-01-12 07:30:51,2026-01-12 07:31:57,0 days 00:01:06
239,PLE1,S,59,2026-01-12 07:32:47,2026-01-12 07:33:15,0 days 00:00:28
240,PLE1,S,60,2026-01-12 08:13:36,2026-01-12 08:13:39,0 days 00:00:03
241,PLE1,S,61,2026-01-12 08:27:14,2026-01-12 08:28:07,0 days 00:00:53
242,PLE1,S,62,2026-01-12 08:29:46,2026-01-12 08:30:24,0 days 00:00:38
243,PLE1,S,63,2026-01-12 08:31:37,2026-01-12 08:32:04,0 days 00:00:27
244,PLE1,S,64,2026-01-12 08:32:22,2026-01-12 08:32:37,0 days 00:00:15
245,PLE1,S,65,2026-01-12 08:32:58,2026-01-12 08:33:15,0 days 00:00:17
246,PLE1,S,66,2026-01-12 08:36:19,2026-01-12 08:36:50,0 days 00:00:31
247,PLE1,S,67,2026-01-12 08:37:55,2026-01-12 08:38:51,0 days 00:00:56
248,PLE1,S,68,2026-01-12 08:45:42,2026-01-12 08:46:00,0 days 00:00:18
249,PLE1,S,69,2026-01-12 08:47:29,2026-01-12 08:47:44,0 days 00:00:15
250,PLE1,S,70,2026-01-12 08:49:20,2026-01-12 08:49:30,0 days 00:00:10
251,PLE1,S,71,2026-01-12 08:49:42,2026-01-12 08:50:05,0 days 00:00:23
252,PLE1,S,72,2026-01-12 08:51:36,2026-01-12 08:51:39,0 days 00:00:03
253,PLE1,S,73,2026-01-12 08:51:51,2026-01-12 08:51:54,0 days 00:00:03
254,PLE1,S,74,2026-01-12 08:52:06,2026-01-12 08:52:34,0 days 00:00:28
255,PLE1,S,75,2026-01-12 08:53:09,2026-01-12 08:53:40,0 days 00:00:31
256,PLE1,S,76,2026-01-12 08:56:59,2026-01-12 08:57:02,0 days 00:00:03
257,PLE1,S,77,2026-01-12 08:57:17,2026-01-12 08:57:27,0 days 00:00:10
258,PLE1,S,78,2026-01-12 08:59:21,2026-01-12 08:59:49,0 days 00:00:28
259,PLE1,S,79,2026-01-12 09:00:09,2026-01-12 09:00:29,0 days 00:00:20
260,PLE1,S,80,2026-01-12 09:00:44,2026-01-12 09:00:49,0 days 00:00:05
261,PLE1,S,81,2026-01-12 09:01:35,2026-01-12 09:02:15,0 days 00:00:40
262,PLE1,S,82,2026-01-12 09:02:30,2026-01-12 09:02:35,0 days 00:00:05
263,PLE1,S,83,2026-01-12 09:04:21,2026-01-12 09:05:07,0 days 00:00:46
264,PLE1,S,84,2026-01-12 09:08:16,2026-01-12 09:09:09,0 days 00:00:53
265,PLE1,S,85,2026-01-12 09:10:18,2026-01-12 09:10:53,0 days 00:00:35
266,PLE1,S,86,2026-01-12 09:11:11,2026-01-12 09:11:48,0 days 00:00:37
267,PLE1,S,87,2026-01-12 09:14:40,2026-01-12 09:14:48,0 days 00:00:08
268,PLE1,S,88,2026-01-12 09:15:10,2026-01-12 09:15:26,0 days 00:00:16
269,PLE1,S,89,2026-01-12 09:17:09,2026-01-12 09:17:55,0 days 00:00:46
270,PLE1,S,90,2026-01-12 09:20:06,2026-01-12 09:20:39,0 days 00:00:33
271,PLE1,S,91,2026-01-12 09:21:24,2026-01-12 09:21:47,0 days 00:00:23
272,PLE1,S,92,2026-01-12 09:21:59,2026-01-12 09:22:07,0 days 00:00:08
273,PLE1,S,93,2026-01-12 09:22:47,2026-01-12 09:23:08,0 days 00:00:21
274,PLE1,S,94,2026-01-12 09:24:03,2026-01-12 09:24:38,0 days 00:00:35
275,PLE1,S,95,2026-01-12 09:25:44,2026-01-12 09:25:57,0 days 00:00:13
276,PLE1,S,96,2026-01-12 09:39:10,2026-01-12 09:39:12,0 days 00:00:02
277,PLE1,S,97,2026-01-12 09:39:27,2026-01-12 09:39:55,0 days 00:00:28
278,PLE1,S,98,2026-01-12 09:40:25,2026-01-12 09:42:59,0 days 00:02:34
279,PLE1,S,99,2026-01-12 09:44:25,2026-01-12 09:44:48,0 days 00:00:23
280,PLE1,S,100,2026-01-12 09:45:03,2026-01-12 09:45:06,0 days 00:00:03
281,PLE1,S,101,2026-01-12 09:45:23,2026-01-12 09:45:26,0 days 00:00:03
282,PLE1,S,102,2026-01-12 09:45:38,2026-01-12 09:45:44,0 days 00:00:06
283,PLE1,S,103,2026-01-12 09:52:02,2026-01-12 09:52:25,0 days 00:00:23
284,PLE1,S,104,2026-01-12 09:52:40,2026-01-12 09:53:16,0 days 00:00:36

In [ ]:
# Eventos a .cvs
from pathlib import Path

OUT_TABLAS = PROJECT_ROOT / "output" / "tablas"
OUT_TABLAS.mkdir(parents=True, exist_ok=True)

df_evento.to_csv(OUT_TABLAS / "df_eventos.csv", index=False)

In [ ]:
# Graficas de eventos por fase 

import plotly.graph_objects as go
from plotly.subplots import make_subplots

def xref_subplot(row):
    return 'x' if row == 1 else f'x{row}'

def yref_subplot(row):
    return 'y domain' if row == 1 else f'y{row} domain'


map_fase_col = {
    'R': 'corriente_r',
    'S': 'corriente_s',
    'T': 'corriente_t'
}

colores_fase = {
    'R': 'red',
    'S': 'green',
    'T': 'blue'
}

maquinas = sorted(df_all['maquina'].unique())

# Figura con 2 filas (una por máquina)
fig = make_subplots(
    rows=len(maquinas),
    cols=1,
    shared_xaxes=False,
    subplot_titles=[f'Máquina {m}' for m in maquinas]
)

# Guardamos índices de traces por (maquina, fase)
trace_idx = {}

# -----------------
# Corrientes
# -----------------
for row, maq in enumerate(maquinas, start=1):

    df_m = df_all[df_all['maquina'] == maq]

    for fase, col in map_fase_col.items():

        visible = (fase == 'R')  # fase inicial

        fig.add_trace(
            go.Scatter(
            x=df_m['temporal_placa'],
            y=df_m[col],
            mode='lines',
            name=f'Fase {fase}',          # nombre genérico
            line=dict(color=colores_fase[fase]),
            visible=visible,
            showlegend=(row == 3)         
        ),
    row=row,
    col=1
)


        trace_idx[(maq, fase)] = len(fig.data) - 1

# Shapes (eventos) por fase
shapes_por_fase = {}

for fase in map_fase_col.keys():

    shapes = []

    for row, maq in enumerate(maquinas, start=1):

        df_e = df_evento[
            (df_evento['maquina'] == maq) &
            (df_evento['fase'] == fase)
        ]

        for _, ev in df_e.iterrows():

            shapes.append(
                dict(
                    type='rect',
                     xref=xref_subplot(row),    
                    yref=yref_subplot(row),
                    x0=ev['Fecha Inicio'],
                    x1=ev['Fecha Fin'],
                    y0=0,
                    y1=1,
                    fillcolor=colores_fase[fase],
                    opacity=0.15,
                    line_width=0
                )
            )

    shapes_por_fase[fase] = shapes

# Dropdown único
botones = []

for fase in map_fase_col.keys():

    visibles = [False] * len(fig.data)

    for maq in maquinas:
        visibles[trace_idx[(maq, fase)]] = True

    botones.append(
        dict(
            label=f'Fase {fase}',
            method='update',
            args=[
                {'visible': visibles},
                {'shapes': shapes_por_fase[fase]}
            ]
        )
    )

# Layout final
fig.update_layout(
    updatemenus=[
        dict(
            buttons=botones,
            direction='down',
            x=1.08,
            y=1,
            showactive=True
        )
    ],
    title='Eventos de corriente por maquina',
    shapes=shapes_por_fase['R']  # fase inicial
)
fig.update_yaxes(title_text='Corriente [A]', row=1, col=1)
fig.update_yaxes(title_text='Corriente [A]', row=2, col=1)

fig.show()

In [ ]:
# Combinacion de fases superpuestas por maquina
import plotly.graph_objects as go
from plotly.subplots import make_subplots

def xref_subplot(row):
    return 'x' if row == 1 else f'x{row}'

def yref_subplot(row):
    return 'y domain' if row == 1 else f'y{row} domain'

# Configuración
map_fase_col = {
    'R': 'corriente_r',
    'S': 'corriente_s',
    'T': 'corriente_t'
}

colores_fase = {
    'R': 'red',
    'S': 'green',
    'T': 'blue'
}

maquinas = sorted(df_all['maquina'].unique())

# Figura con subplots (una fila por máquina)
fig = make_subplots(
    rows=len(maquinas),
    cols=1,
    shared_xaxes=False,
    subplot_titles=[f'Máquina {m}' for m in maquinas]
)


# Corrientes (fases superpuestas)
for row, maq in enumerate(maquinas, start=1):

    df_m = df_all[df_all['maquina'] == maq]

    for fase, col in map_fase_col.items():

        fig.add_trace(
            go.Scatter(
                x=df_m['temporal_placa'],
                y=df_m[col],
                mode='lines',
                name=f'Fase {fase}',
                line=dict(color=colores_fase[fase]),
                showlegend=(row == 1)  # una sola leyenda
            ),
            row=row,
            col=1
        )


# Shapes: eventos por fase y máquina
shapes = []

for fase in map_fase_col.keys():

    for row, maq in enumerate(maquinas, start=1):

        df_e = df_evento[
            (df_evento['maquina'] == maq) &
            (df_evento['fase'] == fase)
        ]

        for _, ev in df_e.iterrows():

            shapes.append(
                dict(
                    type='rect',
                    xref=xref_subplot(row),
                    yref=yref_subplot(row),
                    x0=ev['Fecha Inicio'],
                    x1=ev['Fecha Fin'],
                    y0=0,
                    y1=1,
                    fillcolor=colores_fase[fase],
                    opacity=0.15,
                    line_width=0
                )
            )

# Layout final
fig.update_layout(
    title='Eventos de corriente por máquina (fases superpuestas)',
    shapes=shapes
)

# Títulos de eje Y en todos los subplots
for r in range(1, len(maquinas) + 1):
    fig.update_yaxes(title_text='Corriente [A]', row=r, col=1)

fig.show()